# **Pertemuan 6: Machine Learning Supervised Learning for Classification (Part 1)**

In [ ]:
import numpy as np
import pandas as pd

d:\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# *Classification*

## **Definisi**

<img src = "https://images.datacamp.com/image/upload/v1663850410/Machine_learning_classification_illustration_for_the_email_a993b8df37.png" width = 50%></img>

Klasifikasi adalah salah satu metode dalam *Machine Learning* yang digunakan untuk memprediksi kategori atau label dari suatu data berdasarkan pola yang telah dipelajari sebelumnya. Model klasifikasi bekerja dengan cara belajar dari data latihan *(training data)*, lalu diuji dengan data uji *(test data)*, dan akhirnya digunakan untuk memprediksi data baru yang belum pernah dilihat sebelumnya.

Sebagai contoh, model *Machine Learning* bisa digunakan untuk mendeteksi apakah sebuah email merupakan spam atau bukan spam (ham). Model ini belajar dari email-email sebelumnya yang sudah dikategorikan, lalu menggunakan pola tersebut untuk menentukan kategori email baru.

## **Eager Learners vs. Lazy Learners**  

Dalam klasifikasi *Machine Learning*, terdapat dua jenis pembelajar utama: *eager learners* dan *lazy learners*.  

**Eager Learners**  
Pembelajar giat adalah algoritma *Machine Learning* yang terlebih dahulu membangun model dari data latihan sebelum membuat prediksi pada data baru. Algoritma ini membutuhkan waktu lebih lama dalam proses pelatihan karena berusaha memahami pola dengan baik agar dapat memberikan prediksi yang akurat. Namun, setelah model terbentuk, proses prediksi menjadi lebih cepat.  

Sebagian besar algoritma *Machine Learning* termasuk dalam kategori eager learners, seperti:  
- **Logistic Regression**  
- **Support Vector Machine (SVM)**  
- **Decision Trees**  
- **Artificial Neural Networks (ANN)**  

**Lazy Learners**  
Berbeda dengan eager learners , lazy learners tidak langsung membangun model dari data latihan. Sebaliknya, mereka hanya menyimpan data dan baru mencari pola saat ada permintaan prediksi. Inilah yang membuat mereka disebut "malas"—karena tidak melakukan pekerjaan berat di awal.  Saat akan melakukan prediksi, lazy learners membandingkan data baru dengan seluruh data yang ada, sehingga proses prediksi bisa lebih lambat dibandingkan eager learners.  

Contoh algoritma lazy learners:  
- **K-Nearest Neighbors (KNN)**  
- **Case-Based Reasoning**

## **Perbedaan Klasifikasi dan Regresi dalam Machine Learning**

<img src = "https://images.datacamp.com/image/upload/v1663850409/Difference_between_Classification_and_Regression_98d8677bfd.png" width = 50%></img>

Dalam *Machine Learning*, terdapat empat kategori utama algoritma, yaitu Supervised Learning, Unsupervised Learning, Semi-Supervised Learning, dan Reinforcement Learning. Meskipun klasifikasi dan regresi sama-sama termasuk dalam kategori *Supervised Learning*, keduanya memiliki perbedaan penting.  

- **Klasifikasi** digunakan ketika hasil yang diprediksi berbentuk kategori atau label yang bersifat diskrit.  
  - Contoh: Menentukan apakah sebuah komentar bersentimen positif atau negatif.  
- **Regresi** digunakan ketika hasil yang diprediksi berbentuk nilai numerik yang bersifat kontinu.  
  - Contoh: Memprediksi gaji seseorang berdasarkan tingkat pendidikan, pengalaman kerja, lokasi, dan jabatan.

## **Jenis Klasifikasi**

Secara umum, klasifikasi dalam Machine Learning biasanya dibagi berdasarkan jumlah kategori yang diprediksi, yaitu:  

1. **Klasifikasi Biner (Binary Classification)**  
   - Hanya ada dua kelas atau kategori.  
   - Contoh:  
     - Mendeteksi apakah email adalah spam atau bukan spam.  
     - Memprediksi apakah seseorang sakit atau sehat.

2. **Klasifikasi Multi-Kelas (Multi-Class Classification)**  
   - Memiliki lebih dari dua kelas, tetapi setiap data hanya masuk ke satu kelas.  
   - Contoh:  
     - Mengklasifikasikan jenis hewan sebagai kucing, anjing, atau kelinci.  
     - Memprediksi jurusan yang cocok untuk siswa berdasarkan nilai akademik.   

3. **Klasifikasi Multi-Label (Multi-Label Classification)**  
   - Setiap data bisa masuk ke lebih dari satu kelas.  
   - Contoh:  
     - Sebuah artikel bisa dikategorikan sebagai Teknologi dan Bisnis sekaligus.  
     - Label genre pada film: satu film bisa masuk ke Action dan Sci-Fi sekaligus.

# Read dataset in JSON

In [ ]:
df = pd.read_json('titanic_json.json')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [ ]:
df.shape

(891, 12)

# Preprocessing

Dalam tahap *preprocessing*, kita akan menyiapkan data agar bisa digunakan dalam model *Machine Learning*.

1. **Menentukan Prediktor dan Respon**  
   - Kolom prediktor (fitur yang digunakan untuk memprediksi) adalah:  
     - `Pclass`, `Sex`, `Age`, `SibSp`, `Parch`, `Fare`, `Cabin`, dan `Embarked`.  
   - Kolom respon (target yang diprediksi) adalah:  
     - `Survived` (menunjukkan apakah penumpang selamat atau tidak).  

2. **Mengonversi Data Kategorikal ke Numerik**  
   - Kolom yang berisi data kategori (*non-numerik*) perlu diubah menjadi angka menggunakan teknik categorical label encoding.  
   - Contoh:  
     - `Sex: male` dikonversi menjadi 1.  
     - `Sex: female` dikonversi menjadi 2.  

3. **Menangani *Missing Values***  
   - Kolom kategorik (`Pclass`, `Sex`, `SibSp`, `Parch`, `Cabin`, dan `Embarked`) yang memiliki data hilang akan diisi dengan nilai modus (nilai yang paling sering muncul).  
   - Kolom numerik (`Fare` dan `Age`) yang memiliki data hilang akan diisi dengan nilai median (nilai tengah dari data yang ada).

## 1. Menentukan Prediktor dan Respon

In [ ]:
# Pilih variabel X yang sudah dalam bentuk angka
X_numeric = df[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']]

# Pilih variabel X yang masih bukan angka
X_categoric = df[['Sex', 'Cabin', 'Embarked']]

# Pilih variabel Y
y = df['Survived']

### Cek Missing Value

In [ ]:
X_numeric.isna().sum()

Pclass      0
Age       177
SibSp       0
Parch       0
Fare        0
dtype: int64

In [ ]:
X_categoric.isna().sum()

Sex           0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
y.isna().sum()

0

## 2. Mengonversi Data Kategorikal ke Numerik dengan Label Encoding

Kolom yg ingin kita ubah adalah `Sex`, `Cabin`, dan `Embarked`.

In [ ]:
from sklearn.preprocessing import LabelEncoder
X_encode = X_categoric.apply(LabelEncoder().fit_transform)
X_encode

     Sex  Cabin  Embarked
0      1    147         2
1      0     81         0
2      0    147         2
3      0     55         2
4      1    147         2
..   ...    ...       ...
886    1    147         2
887    0     30         2
888    0    147         2
889    1     60         0
890    1    147         1

[891 rows x 3 columns]

### Cek Missing Value setelah Label Encoding

In [ ]:
X_encode['Embarked'].value_counts()

Embarked
2    644
0    168
1     77
3      2
Name: count, dtype: int64

In [ ]:
X_encode['Cabin'].value_counts()

Cabin
147    687
63       4
145      4
47       4
62       3
      ...
124      1
76       1
72       1
125      1
60       1
Name: count, Length: 148, dtype: int64

## 3. Menangani *Missing Values*

### Ubah angka 147 pada Kolom `Cabin` dan angka 3 pada kolom `Embarked` menjadi NaN

In [ ]:
X_encode['Cabin'].replace(147, np.nan, inplace=True)
X_encode['Embarked'].replace(3, np.nan, inplace=True)
X_encode

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15524\498804481.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_encode['Cabin'].replace(147, np.nan, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_15524\498804481.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_encode['Embarked'].replace(3, np.nan, inplace=True)

     Sex  Cabin  Embarked
0      1    NaN       2.0
1      0   81.0       0.0
2      0    NaN       2.0
3      0   55.0       2.0
4      1    NaN       2.0
..   ...    ...       ...
886    1    NaN       2.0
887    0   30.0       2.0
888    0    NaN       2.0
889    1   60.0       0.0
890    1    NaN       1.0

[891 rows x 3 columns]

In [ ]:
# Gabung hasilnya menjadi satu kesatuan yang utuh
X = pd.concat([X_numeric, X_encode], axis = 1)
X

     Pclass   Age  SibSp  Parch     Fare  Sex  Cabin  Embarked
0         3  22.0      1      0   7.2500    1    NaN       2.0
1         1  38.0      1      0  71.2833    0   81.0       0.0
2         3  26.0      0      0   7.9250    0    NaN       2.0
3         1  35.0      1      0  53.1000    0   55.0       2.0
4         3  35.0      0      0   8.0500    1    NaN       2.0
..      ...   ...    ...    ...      ...  ...    ...       ...
886       2  27.0      0      0  13.0000    1    NaN       2.0
887       1  19.0      0      0  30.0000    0   30.0       2.0
888       3   NaN      1      2  23.4500    0    NaN       2.0
889       1  26.0      0      0  30.0000    1   60.0       0.0
890       3  32.0      0      0   7.7500    1    NaN       1.0

[891 rows x 8 columns]

### Observasi ada tidaknya missing value

In [ ]:
X.isna().sum()

Pclass        0
Age         177
SibSp         0
Parch         0
Fare          0
Sex           0
Cabin       687
Embarked      2
dtype: int64

### Isi missing value kolom numerik `(Age)` dengan median

In [ ]:
X['Age'].fillna(X['Age'].median(), inplace = True)
X

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15524\2752261988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['Age'].fillna(X['Age'].median(), inplace = True)

     Pclass   Age  SibSp  Parch     Fare  Sex  Cabin  Embarked
0         3  22.0      1      0   7.2500    1    NaN       2.0
1         1  38.0      1      0  71.2833    0   81.0       0.0
2         3  26.0      0      0   7.9250    0    NaN       2.0
3         1  35.0      1      0  53.1000    0   55.0       2.0
4         3  35.0      0      0   8.0500    1    NaN       2.0
..      ...   ...    ...    ...      ...  ...    ...       ...
886       2  27.0      0      0  13.0000    1    NaN       2.0
887       1  19.0      0      0  30.0000    0   30.0       2.0
888       3  28.0      1      2  23.4500    0    NaN       2.0
889       1  26.0      0      0  30.0000    1   60.0       0.0
890       3  32.0      0      0   7.7500    1    NaN       1.0

[891 rows x 8 columns]

### Isi missing value kolom kategorik dengan modus

In [ ]:
X['Cabin'].fillna(X['Cabin'].mode()[0], inplace = True)
X['Embarked'].fillna(X['Embarked'].mode()[0], inplace = True)
X

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15524\1258103352.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['Cabin'].fillna(X['Cabin'].mode()[0], inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_15524\1258103352.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['Embarked'].fillna(X['Embarked'].mode()[0], inplace = True)

     Pclass   Age  SibSp  Parch     Fare  Sex  Cabin  Embarked
0         3  22.0      1      0   7.2500    1   47.0       2.0
1         1  38.0      1      0  71.2833    0   81.0       0.0
2         3  26.0      0      0   7.9250    0   47.0       2.0
3         1  35.0      1      0  53.1000    0   55.0       2.0
4         3  35.0      0      0   8.0500    1   47.0       2.0
..      ...   ...    ...    ...      ...  ...    ...       ...
886       2  27.0      0      0  13.0000    1   47.0       2.0
887       1  19.0      0      0  30.0000    0   30.0       2.0
888       3  28.0      1      2  23.4500    0   47.0       2.0
889       1  26.0      0      0  30.0000    1   60.0       0.0
890       3  32.0      0      0   7.7500    1   47.0       1.0

[891 rows x 8 columns]

In [ ]:
X.isna().sum()

Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Sex         0
Cabin       0
Embarked    0
dtype: int64

# Train Test Split

Setelah data 'bersih', saatnya kita bikin model sesuai kreativitas masing-masing!

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.23923, random_state = 455518)

# Evaluation Function

Setelah membangun model klasifikasi, langkah berikutnya adalah mengevaluasi seberapa baik model tersebut dalam memprediksi data baru. Untuk itu, kita memerlukan *evaluation metrics* atau metrik evaluasi yang dapat mengukur performa model secara objektif.  

Beberapa metrik evaluasi yang umum digunakan dalam klasifikasi antara lain:  
1. Accuracy (Akurasi)  
2. Precision (Presisi)  
3. Recall (Sensitivitas & Spesivisitas)  
4. F1-Score  
5. ROC Curve dan AUC (Area Under the Curve)  

Metrik-metrik ini biasanya didasarkan pada *Confusion Matrix* yang menggambarkan bagaimana prediksi model dibandingkan dengan nilai sebenarnya.  

## 1. Confusion Matrix  
Tabel yang digunakan untuk menggambarkan kinerja model klasifikasi dengan membandingkan hasil prediksi dengan nilai aktual.  
<img src = "https://cdn-images-1.medium.com/max/1600/1*I7KT0RgsHaWf0KZETJf56g.png" width = 50%></img>  

## 2. Akurasi (Accuracy)  
Akurasi diperoleh dengan menjawab pertanyaan: **"Dari semua prediksi yang dibuat oleh model, berapa persentase yang benar?"**  

$$
\text{Akurasi} = \frac{TP + TN}{\text{Total jumlah observasi}}
$$

## 3. Presisi (Precision)  
Presisi diperoleh dengan menjawab pertanyaan: **"Dari semua prediksi YES (positif), berapa banyak yang benar?"**  

$$
\text{Presisi} = \frac{TP}{TP + FP}
$$

## 4. Recall / Sensitivitas (Sensitivity)  
Recall atau sensitivitas menjawab pertanyaan: **"Seberapa baik model dalam memprediksi kejadian YES yang sebenarnya?"**  

$$
\text{Sensitivitas} = \frac{TP}{TP + FN}
$$

Sensitivitas sering disebut sebagai **True Positive Rate (TPR)**, yang menunjukkan sejauh mana model dapat menangkap kelas positif dengan benar.

## 5. Spesifisitas (Specificity)  
Spesifisitas menjawab pertanyaan: **"Seberapa baik model dalam memprediksi kejadian NO yang sebenarnya?"**  

$$
\text{Spesifisitas} = \frac{TN}{TN + FP}
$$

Spesifisitas disebut juga **True Negative Rate (TNR)**, yang menunjukkan seberapa baik model dalam mengenali kelas negatif.

## 6. F1 Score
F1 Score digunakan dalam kasus **dataset tidak seimbang**, di mana jumlah satu kelas jauh lebih banyak daripada kelas lainnya.  

F1 Score adalah rata-rata harmonik dari presisi dan recall:

$$
F1 = 2 \times \frac{\text{Presisi} \times \text{Recall}}{\text{Presisi} + \text{Recall}}
$$

F1 Score memberikan keseimbangan antara presisi dan recall, sehingga berguna saat kita ingin mempertimbangkan keduanya secara bersamaan.

## 7. AUC – ROC Curve  
AUC-ROC (Area Under the Curve – Receiver Operating Characteristic) adalah metrik yang mengukur seberapa baik model dapat membedakan antara kelas positif dan negatif dengan menggunakan nilai probabilitas, bukan sekadar prediksi biner (0/1).  

Penggunaan AUC-ROC **lebih cocok jika dataset seimbang**. Jika digunakan pada dataset yang tidak seimbang, interpretasinya bisa salah.  

**Interpretasi nilai AUC:**  
- **Di bawah 0.5** → Model sangat buruk  
- **0.5** → Model acak (random classifier)  
- **Di atas 0.7** → Model cukup baik  
- **Di atas 0.8** → Model kuat  
- **1** → Model sempurna (memprediksi semuanya dengan benar)

### **Tips Memilih Evaluation Metrics**
- Jika data seimbang, gunakan accuracy.
- Jika salah prediksi positif berbahaya, gunakan precision.
- Jika salah prediksi negatif lebih berbahaya, gunakan recall.
- Jika ingin keseimbangan antara precision dan recall, gunakan F1-score.
- Jika ingin menilai performa model di berbagai threshold, gunakan AUC-ROC.

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report
def evaluate_classification(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    print(classification_report(y_true, y_pred))
    return {'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1-score': f1}

# Model

In [ ]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.mixture import GaussianMixture
from sklearn.semi_supervised import LabelPropagation, LabelSpreading

## **Support Vector Machine**

<img src = "https://image.slidesharecdn.com/svm-crashcourse-171128024234/75/Support-Vector-Machine-Classification-Step-by-Step-3-2048.jpg" width = 50%></img>

Support Vector Machine adalah salah satu metode dalam supervised learning yang biasanya digunakan untuk klasifikasi ataupun regresi. Dalam pemodelan klasifikasi, support vector machine memiliki konsep yang lebih matang serta jelas secara matematis dibandingkan dengan teknik klasifikasi lainnya. Support vector machine juga dapat mengatasi masalah klasifikasi dan regresi dengan metode linear maupun non linear.

Algoritma support vector machine digunakan untuk mencari hyperplane terbaik dalam ruang N-dimensi yang secara jelas mengklasifikasikan titik data. Hyperplane adalah sebuah fungsi yang digunakan sebagai pemisah antar kelas yang satu dengan yang lain. Fungsi ini digunakan untuk mengklasifikasikan di dalam ruang kelas dimensi yang lebih tinggi.

Dalam bentuk 2 dimensi, fungsi yang digunakan untuk mengklasifikasikan antar kelas disebut dengan line whereas. Sedangkan fungsi yang digunakan untuk mengklasifikasikan antar kelas dalam bentuk 3 dimensi disebut plane similarly.

### **Konsep Utama dalam SVM**
Beberapa istilah penting dalam SVM adalah:

1. Hyperplane (Bidang Pemisah)
   - Ini adalah garis atau bidang yang membagi dua kelas data.
   - Dalam 2D, hyperplane berupa garis, sedangkan dalam dimensi lebih tinggi, hyperplane bisa berupa bidang atau bentuk lainnya.
   - Rumusnya dalam bentuk linear:  
     $$
     w x + b = 0
     $$
   - Di mana $(w$) adalah bobot, $(x$) adalah fitur data, dan $(b$) adalah bias.

2. Support Vectors
   - Data yang **paling dekat** dengan hyperplane dan sangat berpengaruh dalam menentukan posisi hyperplane.
   - Jika support vector berubah, hyperplane juga akan berubah.

3. Margin
   - Jarak antara hyperplane dengan support vectors.
   - SVM berusaha **memaksimalkan margin** agar pemisahan antar kelas lebih jelas.

4. Hard Margin vs. Soft Margin
   - *Hard Margin:* Memisahkan data **tanpa kesalahan** sama sekali (hanya cocok jika data bisa dipisahkan dengan sempurna).
   - *Soft Margin:* Mengizinkan beberapa kesalahan untuk membuat model lebih **toleran terhadap noise**.

5. Kernel
   - Teknik untuk menangani data yang tidak bisa dipisahkan secara linear.
   - Dengan kernel, data dipetakan ke dimensi yang lebih tinggi agar bisa dipisahkan.
   - Contoh kernel:
     - *Linear Kernel:* Digunakan jika data bisa dipisahkan secara linear.
     - *Polynomial Kernel:* Menggunakan transformasi polinomial untuk menangani data yang lebih kompleks.
     - *RBF (Radial Basis Function) Kernel:* Memetakan data ke dimensi yang sangat tinggi agar bisa dipisahkan.

6. Parameter $( C $)
   - Mengontrol keseimbangan antara margin yang besar dan kesalahan klasifikasi.
   - C besar: Model lebih ketat dan cenderung overfitting.
   - C kecil: Model lebih toleran terhadap kesalahan, cocok untuk generalisasi.

7. Hinge Loss
   - Fungsi yang menghukum kesalahan klasifikasi.
   - Jika titik data diklasifikasikan dengan benar dan berada di luar margin, maka tidak ada penalti.
   - Jika titik data salah diklasifikasikan atau berada dalam margin, maka penalti bertambah.

### **Bagaimana SVM Bekerja?**
1. **Mencari Hyperplane yang Memisahkan Data dengan Margin Terbesar**  
   - Algoritma SVM mencari hyperplane yang dapat memisahkan dua kelas dengan margin maksimal.

2. **Menggunakan Support Vectors**  
   - Support vectors adalah titik-titik yang menentukan posisi dan orientasi hyperplane.
   - Data di luar support vector tidak memengaruhi hyperplane.

3. **Menangani Data yang Tidak Bisa Dipisahkan Secara Linear dengan Kernel Trick**  
   - Jika data tidak bisa dipisahkan dengan garis lurus, SVM menggunakan fungsi kernel untuk memetakan data ke dimensi yang lebih tinggi.

### **Jenis SVM**
1. Linear SVM
   - Cocok jika data bisa dipisahkan dengan garis lurus.
   - Contoh: Membedakan email spam dan non-spam.
2. Non-Linear SVM
   - Cocok jika data tidak bisa dipisahkan dengan garis lurus.
   - Menggunakan fungsi kernel untuk memetakan data ke dimensi yang lebih tinggi.
   - Contoh: Mendeteksi wajah manusia dalam gambar.

### **Parameter**  
Ketika kita membuat model SVM, kita bisa mengatur beberapa parameter yang memengaruhi cara kerja algoritma.

#### **a. `C` (Regularization Parameter)**
- **Fungsi**: Mengontrol keseimbangan antara margin yang besar dan kesalahan klasifikasi.  
- **Nilai besar (`C` tinggi)** → Model lebih ketat, margin lebih kecil, tapi lebih sensitif terhadap noise (overfitting).  
- **Nilai kecil (`C` rendah)** → Model lebih longgar, margin lebih besar, lebih toleran terhadap kesalahan, tetapi bisa menyebabkan underfitting.  
- **Contoh penggunaan:**
  ```python
  from sklearn.svm import SVC
  model = SVC(C=1.0)  # Default C = 1.0
  ```

#### **b. `kernel` (Fungsi Kernel)**
- **Fungsi**: Menentukan cara SVM memproyeksikan data ke dimensi yang lebih tinggi untuk menangani data yang tidak bisa dipisahkan secara linear.
- **Opsi yang tersedia:**
  - `'linear'` → Cocok untuk data yang bisa dipisahkan dengan garis lurus.
  - `'poly'` → Menggunakan transformasi polinomial.
  - `'rbf'` → Menggunakan fungsi Radial Basis Function (RBF), cocok untuk data yang kompleks.
  - `'sigmoid'` → Cocok untuk data berbasis probabilitas.
- **Contoh penggunaan:**
  ```python
  model = SVC(kernel='rbf')  # Default kernel = 'rbf'
  ```

#### **c. `degree` (Tingkat Polinomial untuk `kernel='poly'`)**
- **Fungsi**: Menentukan derajat polinomial yang digunakan jika memilih `kernel='poly'`.  
- **Default**: `degree=3`  
- **Contoh penggunaan:**
  ```python
  model = SVC(kernel='poly', degree=4)  # Menggunakan polinomial tingkat 4
  ```

#### **d. `gamma` (Parameter Kernel RBF dan Polynomial)**
- **Fungsi**: Menentukan seberapa jauh pengaruh satu titik data.
- **Nilai kecil (`gamma` rendah)** → Model lebih halus dan lebih generalisasi.
- **Nilai besar (`gamma` tinggi)** → Model lebih kompleks dan bisa menyebabkan *overfitting*.
- **Opsi:**
  - `'scale'` (default) → Menggunakan **1 / (n_features * var(X))**.
  - `'auto'` → Menggunakan **1 / n_features**.
  - **Nilai numerik** seperti `0.1, 0.01, 0.001`, dll.
- **Contoh penggunaan:**
  ```python
  model = SVC(kernel='rbf', gamma='scale')  # Default gamma = 'scale'
  ```

#### **e. `coef0` (Untuk `poly` dan `sigmoid` Kernel)**
- **Fungsi**: Parameter ini hanya digunakan untuk kernel polynomial dan sigmoid untuk mengontrol bagaimana kernel bekerja.
- **Default**: `coef0=0.0`
- **Contoh penggunaan:**
  ```python
  model = SVC(kernel='poly', coef0=1.0)
  ```

#### **f. `probability` (Mengaktifkan Probabilitas Klasifikasi)**
- **Fungsi**: Jika `True`, model akan menghitung probabilitas prediksi menggunakan *cross-validation*.
- **Catatan**: Menyalakan parameter ini bisa memperlambat pelatihan.
- **Contoh penggunaan:**
  ```python
  model = SVC(probability=True)
  ```

#### **g. `class_weight` (Menangani Data yang Tidak Seimbang)**
- **Fungsi**: Digunakan jika data kelas tidak seimbang, sehingga kelas yang lebih sedikit mendapat bobot lebih tinggi.
- **Opsi:**
  - `None` → Semua kelas berbobot sama.
  - `'balanced'` → Bobot dihitung secara otomatis berdasarkan distribusi kelas.
- **Contoh penggunaan:**
  ```python
  model = SVC(class_weight='balanced')
  ```

### **Atribut dalam SVM (Setelah Model Dilatih)**
Setelah kita melatih model dengan `.fit()`, kita bisa mengakses beberapa atribut penting:

#### **a. `.support_vectors_`**
- **Fungsi**: Menampilkan **support vector** yang menentukan posisi hyperplane.
- **Contoh penggunaan:**
  ```python
  model.fit(X_train, y_train)
  print(model.support_vectors_)
  ```

#### **b. `.n_support_`**
- **Fungsi**: Menampilkan jumlah support vector di setiap kelas.
- **Contoh penggunaan:**
  ```python
  print(model.n_support_)  # Jumlah support vector per kelas
  ```

#### **c. `.dual_coef_`**
- **Fungsi**: Menunjukkan bobot support vector dalam menentukan hyperplane.
- **Contoh penggunaan:**
  ```python
  print(model.dual_coef_)
  ```

#### **d. `.coef_` (Hanya untuk Kernel Linear)**
- **Fungsi**: Menampilkan bobot fitur pada model linear.
- **Catatan**: Hanya tersedia jika menggunakan `kernel='linear'`.
- **Contoh penggunaan:**
  ```python
  linear_svm = SVC(kernel='linear')
  linear_svm.fit(X_train, y_train)
  print(linear_svm.coef_)
  ```

#### **e. `.intercept_`**
- **Fungsi**: Menunjukkan nilai bias `b` dalam persamaan hyperplane.
- **Contoh penggunaan:**
  ```python
  print(model.intercept_)
  ```

In [ ]:
svm_clf = SVC()
svm_clf.fit(x_train, y_train)
svm_pred = svm_clf.predict(x_test)
evaluate_classification(y_test, svm_pred)

              precision    recall  f1-score   support

           0       0.72      0.94      0.82       134
           1       0.80      0.40      0.53        80

    accuracy                           0.74       214
   macro avg       0.76      0.67      0.68       214
weighted avg       0.75      0.74      0.71       214

{'Accuracy': 0.7383177570093458,
 'Precision': 0.8,
 'Recall': 0.4,
 'F1-score': 0.5333333333333333}

## **Decision Tree Classifier**

<img src = "https://th.bing.com/th/id/OIP.Id4dEANgSUHNtB9Gtbz0PwHaGu?w=1024&h=929&rs=1&pid=ImgDetMain" width = 50%></img>

Algoritma decision tree adalah sebuah metode untuk membuat keputusan berdasarkan serangkaian pertanyaan yang terstruktur dalam bentuk pohon keputusan. Setiap simpul pada pohon keputusan mewakili sebuah pertanyaan atau kondisi, dan setiap cabang dari simpul tersebut mewakili jawaban atau aksi yang diambil berdasarkan kondisi tersebut. Proses membuat keputusan dimulai dari simpul paling atas (root node) dan bergerak ke bawah pohon sesuai dengan jawaban atau kondisi yang dipilih pada setiap simpul. Algoritma decision tree biasa digunakan dalam aplikasi machine learning untuk memprediksi keputusan atau klasifikasi suatu data berdasarkan fitur-fitur yang ada. Misalnya, sebuah algoritma decision tree dapat digunakan untuk memprediksi apakah seseorang akan membeli suatu produk berdasarkan fitur seperti usia, pendapatan, dan lokasi tempat tinggal. Decision Tree sangat mudah dipahami dan diinterpretasikan karena menyerupai cara manusia mengambil keputusan. Algoritma ini banyak digunakan di berbagai bidang seperti keuangan, kesehatan, dan pemasaran.

### **Bagaimana Decision Tree Bekerja?**  
1. **Memilih Atribut Terbaik untuk Split (Memecah Data)**  
   - Algoritma mencari atribut yang paling informatif untuk membagi data.
2. **Membagi Dataset Berdasarkan Atribut Tersebut**  
   - Data dibagi menjadi sub-kelompok berdasarkan nilai atribut.
3. **Mengulangi Proses Hingga Memenuhi Kriteria Berhenti**  
   - Proses ini terus dilakukan sampai mencapai leaf node atau memenuhi kondisi tertentu.

### **Parameter**
Ketika kita membuat model Decision Tree di Scikit-Learn, kita bisa mengatur beberapa parameter yang mempengaruhi cara kerja algoritma.  

#### **a. `criterion` (Kriteria Pemilihan Atribut)**
- **Fungsi**: Menentukan cara pemilihan atribut terbaik saat membangun pohon.  
- **Opsi yang tersedia:**
  - `'gini'` (default) → Menggunakan *Gini Impurity* untuk memilih atribut terbaik.  
  - `'entropy'` → Menggunakan *Entropy dan Information Gain* untuk memilih atribut terbaik.  
  - `'log_loss'` → Digunakan untuk *model probabilistik* (tidak umum dalam klasifikasi biasa).  
- **Contoh penggunaan:**
  ```python
  from sklearn.tree import DecisionTreeClassifier
  model = DecisionTreeClassifier(criterion='entropy')
  ```

#### **b. `max_depth` (Kedalaman Maksimum Pohon)**
- **Fungsi**: Menentukan kedalaman maksimum pohon untuk menghindari *overfitting*.  
- **Nilai default**: `None` (akan terus membelah sampai semua node murni).  
- **Semakin dalam pohon, semakin kompleks dan rawan overfitting**.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(max_depth=5)
  ```

#### **c. `min_samples_split` (Minimal Data untuk Split)**
- **Fungsi**: Menentukan jumlah minimal sampel dalam node sebelum dilakukan pemisahan (split).  
- **Default**: `2` (pembagian dilakukan jika ada setidaknya 2 data).  
- **Semakin besar nilai ini, semakin sederhana pohon (mencegah overfitting)**.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(min_samples_split=10)
  ```

#### **d. `min_samples_leaf` (Minimal Data dalam Daun)**
- **Fungsi**: Menentukan jumlah minimal sampel dalam setiap *leaf node*.  
- **Default**: `1` (daun boleh hanya memiliki 1 data).  
- **Semakin besar nilai ini, semakin sederhana model (mencegah overfitting)**.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(min_samples_leaf=5)
  ```

#### **e. `max_features` (Jumlah Fitur Maksimal yang Digunakan per Split)**
- **Fungsi**: Menentukan jumlah fitur maksimum yang dipertimbangkan saat membagi node.  
- **Opsi yang tersedia:**
  - `None` (default) → Menggunakan semua fitur.  
  - `int` → Menggunakan jumlah fitur tertentu.  
  - `float` → Persentase dari jumlah total fitur (misalnya `0.5` berarti menggunakan 50% fitur).  
  - `'sqrt'` → Menggunakan akar kuadrat dari jumlah fitur.  
  - `'log2'` → Menggunakan logaritma basis 2 dari jumlah fitur.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(max_features='sqrt')
  ```

#### **f. `random_state` (Mengontrol Hasil yang Konsisten)**
- **Fungsi**: Mengontrol acak atau tidaknya pemilihan fitur dan data saat membangun pohon.  
- Jika nilai ini diatur, hasilnya akan selalu sama setiap kali dijalankan.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(random_state=42)
  ```

#### **g. `max_leaf_nodes` (Jumlah Maksimal Leaf Node)**
- **Fungsi**: Menentukan jumlah maksimal leaf node dalam pohon.  
- **Semakin kecil nilai ini, semakin sederhana model (mengurangi overfitting)**.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(max_leaf_nodes=10)
  ```

#### **h. `class_weight` (Bobot Kelas untuk Data Tidak Seimbang)**
- **Fungsi**: Mengatur bobot kelas jika dataset tidak seimbang.  
- **Opsi yang tersedia:**
  - `None` → Semua kelas berbobot sama.  
  - `'balanced'` → Bobot kelas dihitung otomatis berdasarkan proporsi kelas.  
  - `{dict}` → Kita bisa memberi bobot secara manual, misalnya `{0: 1, 1: 5}`.  
- **Contoh penggunaan:**
  ```python
  model = DecisionTreeClassifier(class_weight='balanced')
  ```

### **Atribut dalam Decision Tree**  
Setelah kita melatih model (`.fit()`), kita bisa mengakses beberapa atribut yang menyimpan informasi penting.

#### **a. `.feature_importances_` (Pentingnya Setiap Fitur)**
- **Fungsi**: Menampilkan seberapa penting setiap fitur dalam membangun pohon.  
- **Nilai tinggi berarti fitur tersebut sangat berpengaruh dalam prediksi**.  
- **Contoh penggunaan:**
  ```python
  model.fit(X_train, y_train)
  print(model.feature_importances_)
  ```

#### **b. `.tree_` (Struktur Pohon)**
- **Fungsi**: Menyimpan struktur pohon yang sudah dibuat.  
- Bisa digunakan untuk melihat jumlah node, kedalaman pohon, dll.  
- **Contoh penggunaan:**
  ```python
  print(model.tree_.node_count)  # Jumlah node dalam pohon
  print(model.tree_.max_depth)   # Kedalaman maksimum pohon
  ```

#### **c. `.classes_` (Daftar Kelas dalam Model)**
- **Fungsi**: Menampilkan daftar label kelas yang dikenali oleh model.  
- **Contoh penggunaan:**
  ```python
  print(model.classes_)
  ```

#### **d. `.n_classes_` (Jumlah Kelas)**
- **Fungsi**: Menunjukkan jumlah total kelas dalam model.  
- **Contoh penggunaan:**
  ```python
  print(model.n_classes_)
  ```

#### **e. `.n_features_in_` (Jumlah Fitur Input)**
- **Fungsi**: Menunjukkan jumlah fitur yang digunakan dalam pelatihan model.  
- **Contoh penggunaan:**
  ```python
  print(model.n_features_in_)
  ```

In [ ]:
dt_clf = DecisionTreeClassifier(max_depth=5)
dt_clf.fit(x_train, y_train)
dt_pred = dt_clf.predict(x_test)
evaluate_classification(y_test, dt_pred)

              precision    recall  f1-score   support

           0       0.79      0.95      0.86       134
           1       0.87      0.57      0.69        80

    accuracy                           0.81       214
   macro avg       0.83      0.76      0.78       214
weighted avg       0.82      0.81      0.80       214

{'Accuracy': 0.8084112149532711,
 'Precision': 0.8679245283018868,
 'Recall': 0.575,
 'F1-score': 0.6917293233082706}

## **Random Forest Classifier**

<img src = "https://media.geeksforgeeks.org/wp-content/uploads/20240701170624/Random-Forest-Algorithm.webp" width = 50%></img>

Random Forest adalah algoritma *machine learning* berbasis pohon keputusan (*Decision Tree*) yang digunakan untuk klasifikasi dan regresi. Algoritma ini bekerja dengan cara membangun banyak Decision Tree, kemudian menggabungkan hasil prediksi dari semua pohon tersebut untuk membuat keputusan akhir.  

**Mengapa Disebut "Random Forest"?**  
- **Random** → Menggunakan subset acak dari data dan fitur untuk membangun setiap pohon keputusan.  
- **Forest** → Karena terdiri dari banyak pohon keputusan.  

Dengan menggunakan banyak pohon, Random Forest mengurangi overfitting dan meningkatkan akurasi dibandingkan Decision Tree tunggal.  

### **Bagaimana Random Forest Bekerja?**  
**1. Pembentukan Pohon Keputusan (Decision Trees)**
- Data dibagi menjadi beberapa subset secara acak (dengan teknik *bootstrap sampling*).  
- Setiap Decision Tree dilatih dengan subset data yang berbeda.  
- Dalam setiap pohon, hanya subset acak dari fitur yang dipilih untuk membuat split (pembagian cabang).  

**2. Proses Prediksi**
Setelah semua pohon dalam Random Forest selesai dibuat, untuk klasifikasi → Setiap pohon memilih kelas, dan hasil akhir ditentukan dengan voting mayoritas (kelas yang paling banyak dipilih).

**3. Keunggulan "Randomness" dalam Random Forest**
- Pemilihan data acak → Setiap pohon tidak melihat semua data, sehingga mengurangi risiko overfitting.  
- Pemilihan fitur acak → Membantu membuat pohon lebih beragam, sehingga model lebih kuat.  


### **Ilustrasi Sederhana**  
Bayangkan Anda ingin memilih destinasi liburan. Anda bertanya kepada 10 teman yang memiliki pengalaman berbeda:  
- Beberapa teman menyukai pantai, beberapa lebih suka pegunungan.  
- Masing-masing memberi rekomendasi berdasarkan preferensi mereka sendiri.  
- Anda membuat keputusan berdasarkan rekomendasi terbanyak (voting mayoritas).  

Inilah cara kerja Random Forest—mengumpulkan berbagai pendapat untuk mendapatkan keputusan yang lebih akurat.  

### **Asumsi dalam Random Forest**
- Setiap pohon membuat keputusan secara independen → Tidak ada ketergantungan antar pohon.  
- Data diacak → Mencegah model terlalu terpaku pada pola tertentu.  
- Cukup banyak data diperlukan → Supaya setiap pohon belajar pola yang berbeda.  
- Kombinasi banyak pohon menghasilkan prediksi lebih akurat → Mengurangi kesalahan individu.

### **Parameter**  
Saat menggunakan `RandomForestClassifier` atau `RandomForestRegressor` di Scikit-Learn, kita dapat mengatur berbagai parameter untuk menyesuaikan model.  

#### **a. Parameter Terkait Struktur Hutan (Forest Structure)**
1. **`n_estimators`**  
   - Jumlah pohon keputusan (Decision Trees) dalam Random Forest.  
   - Semakin banyak pohon, semakin stabil prediksi, tetapi akan memperlambat eksekusi.  
   - **Default:** `100`  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(n_estimators=200)
     ```

2. **`max_depth`**  
   - Kedalaman maksimum setiap pohon.  
   - Jika `None`, pohon tumbuh sampai semua daun hanya memiliki satu kelas atau jumlah sampel terlalu sedikit.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(max_depth=10)
     ```

3. **`min_samples_split`**  
   - Jumlah minimum sampel yang diperlukan untuk membagi node internal.  
   - **Default:** `2`  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(min_samples_split=5)
     ```

4. **`min_samples_leaf`**  
   - Jumlah minimum sampel yang harus dimiliki oleh setiap daun (leaf node).  
   - **Default:** `1`  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(min_samples_leaf=4)
     ```

#### **b. Parameter Terkait Pemilihan Fitur (Feature Selection)**
5. **`max_features`**  
   - Jumlah maksimum fitur yang dipertimbangkan saat membagi node.  
   - Nilai bisa berupa:  
     - `sqrt` (default untuk `RandomForestClassifier`) → Gunakan `√jumlah fitur`.  
     - `log2` → Gunakan `log2(jumlah fitur)`.  
     - Angka (`int`) → Gunakan sejumlah fitur tertentu.  
     - `None` → Gunakan semua fitur.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(max_features='sqrt')
     ```

6. **`bootstrap`**  
   - Jika `True`, maka data akan dipilih dengan **bootstrap sampling** (pengambilan sampel dengan pengembalian).  
   - Jika `False`, maka semua data digunakan untuk membangun setiap pohon.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(bootstrap=False)
     ```

#### **c. Parameter Terkait Performa & Regularisasi**
7. **`n_jobs`**  
   - Menentukan jumlah CPU yang digunakan untuk training.  
   - `-1` berarti menggunakan semua CPU yang tersedia.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(n_jobs=-1)
     ```

8. **`random_state`**  
   - Menentukan seed untuk menghasilkan hasil yang konsisten setiap kali model dilatih.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(random_state=42)
     ```

9. **`oob_score`**  
   - Jika `True`, maka model akan menggunakan *out-of-bag samples* untuk mengukur performa model.  
   - **Contoh penggunaan:**  
     ```python
     RandomForestClassifier(oob_score=True)
     ```  

#### **d. Parameter Terkait Struktur Pohon**  
10. **`min_weight_fraction_leaf`**  
    - Sama seperti `min_samples_leaf`, tetapi berbasis proporsi dari total jumlah sampel.  
    - Berguna untuk dataset dengan bobot sampel tidak seimbang.  
    - **Default:** `0.0`  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(min_weight_fraction_leaf=0.02)
      ```

11. **`max_leaf_nodes`**  
    - Menentukan jumlah maksimum leaf nodes dalam setiap pohon keputusan.  
    - Jika `None`, pohon tumbuh hingga semua node murni atau `min_samples_split` tercapai.  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(max_leaf_nodes=20)
      ```

12. **`min_impurity_decrease`**  
    - Sebuah node hanya akan di-split jika pengurangannya lebih besar dari nilai ini.  
    - Digunakan untuk mencegah overfitting dengan mengurangi jumlah split tidak perlu.  
    - **Default:** `0.0`  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(min_impurity_decrease=0.01)
      ```

#### **e. Parameter Terkait Performa & Regularisasi**
13. **`ccp_alpha`** *(Complexity Parameter for Pruning)*  
    - Digunakan untuk *pruning post-training*, yaitu memotong cabang yang tidak memberikan manfaat signifikan.  
    - **Default:** `0.0` (tidak ada pruning).  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(ccp_alpha=0.01)
      ```

14. **`warm_start`**  
    - Jika `True`, model akan mempertahankan pohon yang ada dan menambah `n_estimators` baru saat `fit()` dipanggil kembali.  
    - **Default:** `False`  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(n_estimators=100, warm_start=True)
      ```

#### **f. Parameter Terkait Probabilitas & Klasifikasi**
15. **`class_weight`**  
    - Digunakan untuk menangani ketidakseimbangan kelas dalam klasifikasi.  
    - Nilai yang dapat digunakan:  
      - `'balanced'` → Secara otomatis menyesuaikan bobot berdasarkan jumlah sampel dalam setiap kelas.  
      - `'balanced_subsample'` → Seperti `balanced`, tetapi perhitungan dilakukan untuk setiap subset bootstrap.  
      - Dictionary `{class_label: weight}` untuk bobot manual.  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(class_weight='balanced')
      ```

16. **`criterion`**  
    - Digunakan untuk menentukan metode pemilihan split terbaik pada pohon keputusan.  
    - **Untuk klasifikasi (`RandomForestClassifier`)**:  
      - `'gini'` (default) → Menggunakan *Gini Impurity*.  
      - `'entropy'` → Menggunakan *Information Gain*.
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(criterion='entropy')
      ```

#### **g. Parameter Terkait Sampling Data**
17. **`max_samples`**  
    - Menentukan jumlah maksimum sampel yang digunakan untuk membangun setiap pohon dalam bootstrap.  
    - Jika `None`, semua sampel digunakan.  
    - Jika berupa float (0.0 - 1.0), maka dianggap sebagai persentase dari dataset.  
    - Jika berupa integer, berarti jumlah sampel spesifik.  
    - **Contoh penggunaan:**  
      ```python
      RandomForestClassifier(max_samples=0.8)
      ```

### **2. Atribut dalam Random Forest Scikit-Learn**  
Setelah model Random Forest dilatih (`.fit()`), kita dapat mengakses atribut penting untuk memahami bagaimana model bekerja.  

#### **a. Atribut Hasil Training**
1. **`feature_importances_`**  
   - Menunjukkan seberapa penting setiap fitur dalam prediksi.  
   - **Contoh penggunaan:**  
     ```python
     model = RandomForestClassifier()
     model.fit(X_train, y_train)
     print(model.feature_importances_)
     ```

2. **`n_features_in_`**  
   - Menampilkan jumlah fitur yang digunakan dalam training.  
   - **Contoh penggunaan:**  
     ```python
     print(model.n_features_in_)
     ```

3. **`n_classes_`** (hanya untuk klasifikasi)  
   - Menunjukkan jumlah kelas dalam target.  
   - **Contoh penggunaan:**  
     ```python
     print(model.n_classes_)
     ```

#### **b. Atribut Terkait Struktur Model**
4. **`estimators_`**  
   - Berisi semua pohon keputusan individual dalam Random Forest.  
   - Kita dapat mengakses pohon tertentu dengan `model.estimators_[index]`.  
   - **Contoh penggunaan:**  
     ```python
     first_tree = model.estimators_[0]
     print(first_tree)
     ```

5. **`oob_score_`** (jika `oob_score=True`)  
   - Menunjukkan skor validasi menggunakan *out-of-bag samples*.  
   - **Contoh penggunaan:**  
     ```python
     print(model.oob_score_)
     ```

In [ ]:
rf_clf = RandomForestClassifier(n_estimators=100, max_depth=5)
rf_clf.fit(x_train, y_train)
rf_pred = rf_clf.predict(x_test)
evaluate_classification(y_test, rf_pred)

              precision    recall  f1-score   support

           0       0.81      0.94      0.87       134
           1       0.86      0.64      0.73        80

    accuracy                           0.83       214
   macro avg       0.84      0.79      0.80       214
weighted avg       0.83      0.83      0.82       214

{'Accuracy': 0.8271028037383178,
 'Precision': 0.864406779661017,
 'Recall': 0.6375,
 'F1-score': 0.7338129496402878}

## **MLP Classifier (ANN)**

<img src = "https://michael-fuchs-python.netlify.app/post/2021-02-03-nn-multi-layer-perceptron-classifier-mlpclassifier_files/p110p3.png" width = 50%></img>

 Multi-Layer Perceptron (MLP) adalah jenis jaringan saraf tiruan (Artificial Neural Network, ANN) yang digunakan untuk tugas klasifikasi dan regresi. MLP sangat efektif dalam menangani hubungan *non-linear* antara fitur dan target, sehingga sering digunakan dalam berbagai aplikasi seperti pengenalan gambar, klasifikasi teks, dan pemrosesan suara.  

### **Arsitektur Multi-Layer Perceptron (MLP)**  
MLP terdiri dari beberapa lapisan neuron yang terhubung, dengan tiga jenis utama:  

#### **1. Input Layer (Lapisan Input)**  
- Lapisan ini menerima fitur dari dataset.  
- Setiap neuron dalam input layer mewakili satu fitur dalam data.  
- Jumlah neuron di input layer = jumlah fitur dalam dataset.  

#### **2. Hidden Layer (Lapisan Tersembunyi)**  
- Lapisan ini bertanggung jawab untuk belajar pola dari data.  
- MLP dapat memiliki satu atau lebih hidden layer.  
- Jumlah neuron dalam setiap hidden layer ditentukan sebagai *hyperparameter* yang bisa diatur.  
- Setiap neuron di hidden layer menggunakan fungsi aktivasi (seperti ReLU atau tanh) untuk menangani hubungan *non-linear* dalam data.  

#### **3. Output Layer (Lapisan Output)**  
- Lapisan ini menghasilkan prediksi akhir berdasarkan hasil dari hidden layer.  
- Jumlah neuron di output layer tergantung pada jenis tugas klasifikasi:  
  - Klasifikasi biner → 1 neuron dengan fungsi aktivasi sigmoid (menghasilkan probabilitas antara 0 dan 1).  
  - Klasifikasi multi-kelas → Sejumlah neuron sesuai jumlah kelas, menggunakan fungsi aktivasi softmax.  

### **Bagaimana MLP Bekerja?**  
MLP bekerja melalui beberapa tahap utama:  

#### **1. Inisialisasi Bobot dan Bias**  
- Semua bobot (weights) dan bias dalam jaringan diberikan nilai awal acak yang kecil.  

#### **2. Forward Propagation**  
- Data dari input layer melewati hidden layers, dihitung dengan:  
  $$
  Z = W \cdot X + B
  $$
  - $( Z $) = hasil sebelum aktivasi  
  - $( W $) = bobot neuron  
  - $( X $) = input dari lapisan sebelumnya  
  - $( B $) = bias  
- Fungsi aktivasi seperti ReLU atau sigmoid digunakan untuk menambahkan non-linearitas dalam jaringan.  

#### **3. Perhitungan Loss Function**  
- Setelah forward propagation, model membandingkan hasil prediksi dengan label sebenarnya menggunakan fungsi loss.  
- Untuk klasifikasi, biasanya digunakan Cross-Entropy Loss:  
  $$
  L = - \sum (y \log(\hat{y}))
  $$
  - $( y $) = label sebenarnya  
  - $( \hat{y} $) = prediksi model  

#### **4. Backpropagation (Propagasi Balik)**  
- Mengupdate bobot agar model lebih akurat dalam prediksi.  
- Menggunakan *Gradient Descent* dan turunan fungsi loss untuk menghitung perubahan bobot.  

#### **5. Prediksi**  
- Setelah model dilatih, ia dapat digunakan untuk memprediksi data baru menggunakan forward propagation.

### **Parameter**  

Scikit-Learn menyediakan **MLPClassifier** untuk melakukan klasifikasi menggunakan Multi-Layer Perceptron (MLP). Model ini memiliki beberapa **parameter** yang dapat dikonfigurasi dan **atribut** yang dapat diakses setelah pelatihan.   

#### **1.1 Struktur Jaringan**
- `hidden_layer_sizes`:  
  - Menentukan jumlah neuron di setiap *hidden layer*.  
  - Format: *tuple* → `(neurons_layer1, neurons_layer2, ... )`.  
  - Contoh:  
    ```python
    MLPClassifier(hidden_layer_sizes=(100, 50))  # 2 hidden layers dengan 100 dan 50 neuron
    ```
  - **Default**: `(100,)` → 1 hidden layer dengan 100 neuron.  

#### **1.2 Fungsi Aktivasi**  
- `activation`:  
  - Fungsi aktivasi untuk *hidden layer*.  
  - Pilihan:  
    - `"identity"` → Fungsi linear (tidak ada transformasi).  
    - `"logistic"` → Sigmoid (cocok untuk output probabilitas).  
    - `"tanh"` → Hyperbolic tangent (cocok untuk data skala -1 hingga 1).  
    - `"relu"` → Rectified Linear Unit (umum digunakan, cepat dan efektif).  
  - **Default**: `"relu"`.  
  - Contoh:  
    ```python
    MLPClassifier(activation="tanh")
    ```

#### **1.3 Algoritma Optimasi**  
- `solver`:  
  - Algoritma optimasi untuk pelatihan bobot.  
  - Pilihan:  
    - `"lbfgs"` → Solver berbasis optimasi kuasi-Newton (baik untuk dataset kecil).  
    - `"sgd"` → Stochastic Gradient Descent.  
    - `"adam"` → Adaptive Moment Estimation (cocok untuk sebagian besar kasus).  
  - **Default**: `"adam"`.  
  - Contoh:  
    ```python
    MLPClassifier(solver="sgd")
    ```

#### **1.4 Parameter Gradient Descent**  
- `learning_rate`:  
  - Cara pembaruan bobot dilakukan selama pelatihan.  
  - Pilihan:  
    - `"constant"` → Kecepatan belajar tetap.  
    - `"invscaling"` → Berkurang seiring iterasi.  
    - `"adaptive"` → Berkurang saat loss tidak membaik.  
  - **Default**: `"constant"`.  

- `learning_rate_init`:  
  - **Tingkat awal pembelajaran**.  
  - Default: `0.001`.  
  - Contoh:  
    ```python
    MLPClassifier(learning_rate_init=0.01)
    ```

#### **1.5 Regularisasi dan Overfitting Control**  
- `alpha`:  
  - **Regularisasi L2** untuk menghindari overfitting.  
  - Default: `0.0001`.  
  - Contoh:  
    ```python
    MLPClassifier(alpha=0.01)
    ```
- `max_iter`:  
  - **Jumlah maksimum iterasi** dalam pelatihan.  
  - Default: `200`.  
  - Contoh:  
    ```python
    MLPClassifier(max_iter=500)
    ```

#### **1.6 Parameter Lainnya**  
- `batch_size`:  
  - Jumlah sampel yang diproses dalam satu iterasi (hanya untuk solver `sgd` dan `adam`).  
  - Default: `auto` (menggunakan `min(200, n_samples)`).  

- `random_state`:  
  - Menentukan angka acak untuk mendapatkan hasil yang sama setiap kali model dijalankan.  
  - Contoh:  
    ```python
    MLPClassifier(random_state=42)
    ```

### **2. Atribut dalam `MLPClassifier`**  

Setelah model dilatih menggunakan `.fit(X, y)`, beberapa atribut dapat diakses:

#### **2.1 Bobot dan Bias**
- `coefs_`:  
  - Daftar bobot (weights) untuk setiap lapisan jaringan.  
  - Contoh:  
    ```python
    model = MLPClassifier().fit(X_train, y_train)
    print(model.coefs_)
    ```

- `intercepts_`:  
  - Daftar bias untuk setiap lapisan jaringan.  

#### **2.2 Hasil Pelatihan**
- `loss_`:  
  - Nilai loss terakhir setelah pelatihan selesai.  

- `n_iter_`:  
  - Jumlah iterasi yang dijalankan selama pelatihan.  

- `out_activation_`:  
  - Fungsi aktivasi output layer (misalnya `"softmax"` untuk multi-kelas).  

#### **2.3 Kinerja Model**
- `n_layers_`:  
  - Jumlah total lapisan, termasuk input, hidden, dan output.  

- `n_outputs_`:  
  - Jumlah kelas dalam output.

In [ ]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000)
mlp_clf.fit(x_train, y_train)
mlp_pred = mlp_clf.predict(x_test)
evaluate_classification(y_test, mlp_pred)

              precision    recall  f1-score   support

           0       0.84      0.89      0.87       134
           1       0.79      0.72      0.76        80

    accuracy                           0.83       214
   macro avg       0.82      0.81      0.81       214
weighted avg       0.83      0.83      0.83       214

{'Accuracy': 0.8271028037383178,
 'Precision': 0.7945205479452054,
 'Recall': 0.725,
 'F1-score': 0.7581699346405228}

## **Discriminant Analysis**

<img src = "https://th.bing.com/th/id/R.49f3413517ead831a56146de6f9308a9?rik=zcBekJYvkbtepg&riu=http%3a%2f%2fwww.sthda.com%2fenglish%2fsthda-upload%2ffigures%2fmachine-learning-essentials%2f032-discriminant-analysis-comparing-lda-qda-and-mda-1.png&ehk=IqHC1QVBrXjb%2b285kE2EAI2xim7ZinCiS4%2bpOwd5m2U%3d&risl=&pid=ImgRaw&r=0" width = 50%></img>

 Discriminant Analysis adalah teknik statistik yang digunakan untuk menganalisis perbedaan antara dua atau lebih kelas dan membuat model prediksi berdasarkan perbedaan tersebut. Tujuan utama dari metode ini adalah memisahkan kelas-kelas dalam dataset dengan cara mencari kombinasi linear dari fitur yang memaksimalkan perbedaan antar kelas sambil tetap mempertahankan variasi dalam kelas. Discriminant Analysis sering digunakan dalam klasifikasi dan pengurangan dimensi, terutama ketika asumsi distribusi data normal (Gaussian) dapat dipenuhi.  

### **Jenis-Jenis Discriminant Analysis**  

Ada beberapa varian utama dari Discriminant Analysis, yaitu:  

#### **1. Linear Discriminant Analysis (LDA)**  
LDA adalah teknik yang mencari kombinasi linear dari fitur untuk memaksimalkan pemisahan antar kelas sambil tetap mempertahankan variasi dalam kelas. LDA diasumsikan bekerja dengan distribusi Gaussian dan kovarians yang sama antar kelas.  

**Cara Kerja LDA**  
1. Menghitung mean dan varians dari setiap kelas dalam dataset.  
2. Menghitung matriks kovarians antar kelas untuk mengetahui bagaimana data tersebar.  
3. Membangun garis pemisah linear (decision boundary) dengan memaksimalkan rasio antara variasi antar kelas dan variasi dalam kelas.  
4. Menggunakan fungsi diskriminan untuk mengklasifikasikan data baru.

**Parameter Utama dalam LDA**
Berikut adalah beberapa parameter penting dalam **LDA**:

| Parameter | Deskripsi | Default |
|-----------|----------|---------|
| `solver` | Algoritma yang digunakan untuk menghitung LDA. Pilihan: `'svd'`, `'lsqr'`, `'eigen'`. | `'svd'` |
| `shrinkage` | Teknik regularisasi untuk menghindari overfitting. Hanya berlaku untuk solver `'lsqr'` atau `'eigen'`. Bisa berupa `'auto'`, `float`, atau `None`. | `None` |
| `priors` | Probabilitas awal dari setiap kelas. Jika `None`, dihitung dari data. | `None` |
| `n_components` | Jumlah dimensi baru setelah reduksi dimensi. Harus ≤ jumlah kelas - 1. | `None` |
| `store_covariance` | Menyimpan matriks kovarians antar kelas jika `True`. | `False` |
| `tol` | Toleransi untuk menentukan singularitas matriks kovarians. | `0.0001` |

**Atribut LDA**  
Setelah model dilatih, kita dapat mengakses beberapa atribut penting:

| Atribut | Deskripsi |
|---------|----------|
| `coef_` | Koefisien regresi linear untuk setiap kelas. |
| `intercept_` | Intersep dari model untuk setiap kelas. |
| `means_` | Mean dari setiap fitur untuk setiap kelas. |
| `priors_` | Probabilitas awal dari setiap kelas. |
| `scalings_` | Transformasi skala untuk fitur (hanya tersedia jika `solver='eigen'`). |
| `xbar_` | Mean dari seluruh data pelatihan. |


#### **2. Quadratic Discriminant Analysis (QDA)**  
QDA adalah varian dari LDA yang tidak mengasumsikan kovarians antar kelas sama. Dengan kata lain, setiap kelas memiliki matriks kovariansnya sendiri. Oleh karena itu, pemisahan antara kelas tidak lagi berupa garis lurus, melainkan kurva kuadratik.  

**Cara Kerja QDA**  
1. Menghitung mean dan matriks kovarians terpisah untuk setiap kelas.  
2. Menggunakan fungsi diskriminan kuadratik untuk membuat keputusan klasifikasi.

**Parameter Utama dalam QDA**  
Berikut adalah parameter utama dalam **QDA**:

| Parameter | Deskripsi | Default |
|-----------|----------|---------|
| `priors` | Probabilitas awal dari setiap kelas. Jika `None`, dihitung dari data. | `None` |
| `reg_param` | Parameter regularisasi untuk matriks kovarians, mencegah singularitas. | `0.0` |
| `store_covariance` | Jika `True`, menyimpan matriks kovarians untuk setiap kelas. | `False` |
| `tol` | Toleransi untuk menangani kasus singular dalam inversi matriks kovarians. | `1e-4` |

**Atribut QDA**  
Setelah model dilatih, berikut atribut yang bisa diakses:

| Atribut | Deskripsi |
|---------|----------|
| `means_` | Mean dari setiap fitur untuk setiap kelas. |
| `priors_` | Probabilitas awal dari setiap kelas. |
| `covariance_` | Matriks kovarians untuk setiap kelas (jika `store_covariance=True`). |

#### **3. Mixture Discriminant Analysis (MDA)**
MDA adalah bentuk lebih kompleks dari Discriminant Analysis yang menggunakan model campuran Gaussian (Gaussian Mixture Model - GMM) untuk memperkirakan distribusi kelas. Alih-alih mengasumsikan bahwa setiap kelas hanya memiliki satu distribusi Gaussian seperti LDA dan QDA, MDA membagi setiap kelas menjadi beberapa distribusi Gaussian, memungkinkan pemodelan yang lebih fleksibel.  

**Cara Kerja MDA**  
1. Setiap kelas dipecah menjadi beberapa sub-kelompok menggunakan Gaussian Mixture Model.  
2. Setiap sub-kelompok diberi bobot berdasarkan probabilitasnya dalam kelas tersebut.  
3. Keputusan klasifikasi dibuat berdasarkan kombinasi semua sub-kelompok dalam satu kelas.

**Parameter Utama dalam GMM (untuk MDA)**

| Parameter | Deskripsi | Default |
|-----------|----------|---------|
| `n_components` | Jumlah distribusi Gaussian dalam model. | `1` |
| `covariance_type` | Jenis matriks kovarians (`'full'`, `'tied'`, `'diag'`, `'spherical'`). | `'full'` |
| `tol` | Toleransi untuk konvergensi algoritma EM. | `1e-3` |
| `reg_covar` | Regularisasi untuk mencegah singularitas kovarians. | `1e-6` |
| `max_iter` | Maksimum jumlah iterasi untuk algoritma EM. | `100` |
| `random_state` | Seed untuk hasil yang dapat direproduksi. | `None` |

**Atribut GMM (untuk MDA)**

| Atribut | Deskripsi |
|---------|----------|
| `means_` | Mean dari setiap distribusi Gaussian. |
| `covariances_` | Matriks kovarians untuk setiap distribusi Gaussian. |
| `weights_` | Bobot dari setiap distribusi Gaussian dalam campuran. |

#### **Perbandingan LDA, QDA, dan MDA**  

| Metode | Asumsi Kovarians | Bentuk Decision Boundary | Fleksibilitas | Risiko Overfitting | Cocok untuk |  
|--------|----------------|--------------------|--------------|----------------|----------------|  
| **LDA** | Sama untuk semua kelas | Linear | Rendah | Rendah | Data dengan struktur linear |  
| **QDA** | Berbeda antar kelas | Kuadratik | Sedang | Sedang | Data dengan struktur lebih kompleks |  
| **MDA** | Berbeda dan bisa memiliki banyak sub-kelompok dalam satu kelas | Non-linear | Tinggi | Tinggi | Data dengan distribusi non-Gaussian atau kompleks |

In [ ]:
lda_clf = LinearDiscriminantAnalysis()
lda_clf.fit(x_train, y_train)
qda_pred = lda_clf.predict(x_test)
evaluate_classification(y_test, qda_pred)

              precision    recall  f1-score   support

           0       0.81      0.90      0.85       134
           1       0.79      0.65      0.71        80

    accuracy                           0.80       214
   macro avg       0.80      0.77      0.78       214
weighted avg       0.80      0.80      0.80       214

{'Accuracy': 0.8037383177570093,
 'Precision': 0.7878787878787878,
 'Recall': 0.65,
 'F1-score': 0.7123287671232876}

In [ ]:
qda_clf = QuadraticDiscriminantAnalysis()
qda_clf.fit(x_train, y_train)
qda_pred = qda_clf.predict(x_test)
evaluate_classification(y_test, qda_pred)

              precision    recall  f1-score   support

           0       0.87      0.87      0.87       134
           1       0.78      0.78      0.78        80

    accuracy                           0.84       214
   macro avg       0.83      0.82      0.82       214
weighted avg       0.84      0.84      0.84       214

{'Accuracy': 0.8364485981308412,
 'Precision': 0.7848101265822784,
 'Recall': 0.775,
 'F1-score': 0.779874213836478}

MDA tidak tersedia secara langsung di Scikit-Learn, tetapi dapat dibuat menggunakan Gaussian Mixture Model (GMM) sebagai pengganti:

In [ ]:
gmm = GaussianMixture(n_components=2)
gmm.fit(x_train, y_train)
gmm_pred = gmm.predict(x_test)
evaluate_classification(y_test, gmm_pred)

              precision    recall  f1-score   support

           0       0.72      0.92      0.80       134
           1       0.74      0.39      0.51        80

    accuracy                           0.72       214
   macro avg       0.73      0.65      0.66       214
weighted avg       0.72      0.72      0.69       214

{'Accuracy': 0.719626168224299,
 'Precision': 0.7380952380952381,
 'Recall': 0.3875,
 'F1-score': 0.5081967213114754}

## **Semi-Supervised Learning**

Label Propagation dan Label Spreading adalah dua algoritma semi-supervised learning (pembelajaran semi-terawasi) yang digunakan untuk menebak label sampel yang tidak berlabel berdasarkan hubungan antara data berlabel dan tidak berlabel. Kedua metode ini menggunakan **graf** untuk menyebarkan informasi dari data yang sudah memiliki label ke data yang belum berlabel.

**Contoh Sederhana:**
Bayangkan kamu punya satu kelas dengan 30 murid. Kamu tahu bahwa 10 orang di antara mereka pintar dalam matematika, tapi sisanya kamu tidak tahu. Nah, bagaimana caranya menebak siapa lagi yang pintar dalam matematika?

Kamu bisa melihat siapa yang sering duduk bersama, siapa yang sering belajar bersama, dan siapa yang punya pola mirip dengan anak-anak yang sudah diketahui pintar. Berdasarkan ini, kamu bisa menebak siapa lagi yang kemungkinan besar pintar dalam matematika.

### **1. Label Propagation**  
**Definisi:**  
Label Propagation adalah algoritma berbasis graf yang menyebarkan label dari data berlabel ke data tak berlabel berdasarkan hubungan kedekatan antar sampel. Metode ini menggunakan pendekatan propagasi label murni, di mana label akan menyebar **tanpa adanya regularisasi tambahan**.  

**Bagaimana Cara Kerjanya?**
1. **Membangun Graf**  
   - Algoritma membuat graf berdasarkan hubungan antar sampel menggunakan metode **kNN (k-nearest neighbors)** atau **Kernel RBF (Radial Basis Function)**.
  
2. **Menetapkan Bobot Antar Sampel**  
   - Bobot antar sampel dihitung berdasarkan kedekatan atau kesamaan fitur.

3. **Propagasi Label**  
   - Label dari sampel yang berlabel akan menyebar ke sampel yang tidak berlabel berdasarkan bobot antar node.
   - Proses ini berulang hingga konvergen atau mencapai jumlah iterasi maksimum.

4. **Prediksi Label**  
   - Setelah propagasi selesai, setiap sampel mendapatkan label berdasarkan bobot yang paling kuat.

### **2. Label Spreading**  
**Definisi:**  
Label Spreading mirip dengan Label Propagation, tetapi dengan **regularisasi tambahan** agar penyebaran label tidak terlalu ekstrem. Metode ini lebih stabil dibandingkan Label Propagation karena menggunakan pendekatan **clamping factor** untuk menjaga label asli tetap stabil selama iterasi.  

**Bagaimana Cara Kerjanya?**
1. **Membangun Graf**  
   - Sama seperti Label Propagation, algoritma membangun graf berdasarkan hubungan antar sampel.

2. **Regularisasi dengan Clamping Factor**  
   - Label yang sudah ada tidak langsung menyebar secara penuh, tetapi dikendalikan dengan faktor regularisasi.
   - Clamping factor mengontrol seberapa banyak label asli tetap dipertahankan selama proses propagasi.

3. **Penyebaran Label**  
   - Label dari sampel yang berlabel disebarkan ke data yang tidak berlabel dengan mempertimbangkan regularisasi.
   - Proses ini berulang hingga konvergen.

4. **Prediksi Label**  
   - Setelah iterasi selesai, setiap sampel mendapatkan label berdasarkan bobot tertinggi.

## **Perbandingan Label Propagation vs Label Spreading**
| **Fitur** | **Label Propagation** | **Label Spreading** |
|-----------|----------------------|----------------------|
| **Regularisasi** | Tidak ada (murni propagasi) | Ada (menggunakan clamping factor) |
| **Kelebihan** | Cepat dalam menyebarkan label | Lebih stabil dan menghindari overfitting |
| **Kekurangan** | Rentan terhadap data noise dan outlier | Lebih lambat dibandingkan Label Propagation |
| **Cocok Untuk** | Dataset kecil dengan hubungan yang jelas antar data | Dataset dengan noise atau distribusi yang kompleks |

### **Parameter Utama dalam Label Propagation dan Label Spreading**  

| Parameter | Deskripsi | Default |
|-----------|----------|---------|
| `kernel` | Metode untuk membangun graf. Pilihan: `'rbf'`, `'knn'`. | `'rbf'` |
| `gamma` | Parameter untuk kernel RBF (hanya berlaku jika `kernel='rbf'`). | `20` |
| `n_neighbors` | Jumlah tetangga terdekat untuk `kernel='knn'`. | `7` |
| `alpha` | Hanya untuk Label Spreading. Mengontrol seberapa banyak label asli tetap dipertahankan (`0.0` berarti propagasi penuh, `1.0` berarti tidak menyebar sama sekali). | `0.2` |
| `max_iter` | Jumlah iterasi maksimum untuk penyebaran label. | `30` |
| `tol` | Toleransi konvergensi. Jika perubahan prediksi di iterasi berikutnya kecil, iterasi berhenti lebih awal. | `1e-3` |

**Perbedaan utama:**
- Label Propagation langsung menyebarkan label tanpa mempertimbangkan perubahan besar.
- Label Spreading memiliki `alpha`, yang memungkinkan model untuk lebih stabil dengan mempertahankan sebagian informasi awal. `alpha` = Parameter unik pada Label Spreading! Menentukan seberapa banyak label baru dipengaruhi oleh label lama. Nilai 0 = hanya berdasarkan propagasi baru, nilai 1 = hanya berdasarkan label awal.

### **Atribut yang Dapat Diakses Setelah Pelatihan**  

| Atribut | Deskripsi |
|---------|----------|
| `label_distributions_` | Probabilitas setiap sampel untuk termasuk dalam setiap kelas. |
| `transduction_` | Prediksi label untuk seluruh data, termasuk yang awalnya tidak berlabel. |
| `X_` | Data fitur yang digunakan dalam pelatihan. |

In [ ]:
lp_clf = LabelPropagation(kernel='rbf', gamma=0.1)
lp_clf.fit(x_train, y_train)
lp_pred = lp_clf.predict(x_test)
evaluate_classification(y_test, lp_pred)

              precision    recall  f1-score   support

           0       0.75      0.87      0.80       134
           1       0.69      0.51      0.59        80

    accuracy                           0.73       214
   macro avg       0.72      0.69      0.70       214
weighted avg       0.73      0.73      0.72       214

{'Accuracy': 0.7336448598130841,
 'Precision': 0.6949152542372882,
 'Recall': 0.5125,
 'F1-score': 0.5899280575539568}

In [ ]:
ls_clf = LabelSpreading(kernel='knn', n_neighbors=5, max_iter=1000)
ls_clf.fit(x_train, y_train)
ls_pred = ls_clf.predict(x_test)
evaluate_classification(y_test, ls_pred)

              precision    recall  f1-score   support

           0       0.74      0.78      0.76       134
           1       0.60      0.54      0.57        80

    accuracy                           0.69       214
   macro avg       0.67      0.66      0.66       214
weighted avg       0.69      0.69      0.69       214

{'Accuracy': 0.6915887850467289,
 'Precision': 0.5972222222222222,
 'Recall': 0.5375,
 'F1-score': 0.5657894736842105}

## **All Models**

In [ ]:
# Model
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.mixture import GaussianMixture
from sklearn.semi_supervised import LabelPropagation, LabelSpreading

# Metrics evaluasi
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def auto_model(x_kereta, y_kereta, x_ujian, y_ujian):
  # Tulis semua model yg mau dibikin jadi sebuah list kayak gini
  daftar_model_kita = [SVC(), DecisionTreeClassifier(), RandomForestClassifier(),MLPClassifier(), LinearDiscriminantAnalysis(), QuadraticDiscriminantAnalysis(), GaussianMixture(n_components=2), LabelPropagation(), LabelSpreading()]

  # Siapin list buat nyimpen nilai metrics nya, bebas sih mau pilih apa aja
  akurasi = []
  formula_1 = []
  temennya_akurasi = []
  recall_recall = []

  # Looping deh
  for model in daftar_model_kita:
    # Di fit
    model.fit(x_train, y_train)

    # Prediksi dataset ujian
    prediksi_model_kita = model.predict(x_test)
    akurasi.append(accuracy_score(y_true = y_test, y_pred = prediksi_model_kita))
    formula_1.append(f1_score(y_true = y_test, y_pred = prediksi_model_kita))
    temennya_akurasi.append(precision_score(y_true = y_test, y_pred = prediksi_model_kita))
    recall_recall.append(recall_score(y_true = y_test, y_pred = prediksi_model_kita))

  # Jadiin sebuah dataframe biar keren gituloh
  hasil = {
    'model' : daftar_model_kita,
    'akurasi' : akurasi,
    'f1_score' : formula_1,
    'presisi' : temennya_akurasi,
    'recall' : recall_recall
  }

  # Balikin hasilnya
  return(pd.DataFrame(hasil))

In [ ]:
# Saatnya kita uji
hasil = auto_model(x_train, y_train, x_test, y_test)

d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer

In [ ]:
hasil.sort_values(by='akurasi', ascending=False)

,model,akurasi,f1_score,presisi,recall
2,"(DecisionTreeClassifier(max_features='sqrt', r...",0.845794,0.784314,0.821918,0.7500
5,QuadraticDiscriminantAnalysis(),0.836449,0.779874,0.784810,0.7750
1,DecisionTreeClassifier(),0.827103,0.748299,0.820896,0.6875
4,LinearDiscriminantAnalysis(),0.803738,0.712329,0.787879,0.6500
3,MLPClassifier(),0.799065,0.707483,0.776119,0.6500
0,SVC(),0.738318,0.533333,0.800000,0.4000
6,GaussianMixture(n_components=2),0.719626,0.508197,0.738095,0.3875
8,LabelSpreading(),0.663551,0.506849,0.560606,0.4625
7,LabelPropagation(),0.658879,0.503401,0.552239,0.4625

### Bonus content: gunakan Cross Validation, tidak perlu pakai train_test_split!

Tujuannya pakai CV sesuai namanya, yaitu untuk validasi hasil akhir.

Misal kita sudah punya 2 kandidat model, yaitu Decision Tree vs SVC. Secara akurasi bagusan Decision Tree, tapi secara F1 score bagusan SVC.

Untuk memastikan, kita bisa lihat rata2 nilai cross validationnya. CV itu intinya ngecek model kita berulang kali (bukan cuma 1 kali).

In [ ]:
# Ini ni salah satunya
from sklearn.model_selection import KFold, cross_val_score

def auto_model_pake_cv(X, y):
  # Tulis semua model yg mau dibikin jadi sebuah list kayak gini
  daftar_model_kita = [SVC(), DecisionTreeClassifier(), RandomForestClassifier(),MLPClassifier(), LinearDiscriminantAnalysis(), QuadraticDiscriminantAnalysis(), GaussianMixture(n_components=2), LabelPropagation(), LabelSpreading()]

  # Bikin CV buat daftar kerja
  # CV ini nanti otomatis dipakai oleh model
  cv_kita = KFold(n_splits = 3)

  # Siapin list buat nyimpen nilai metrics nya, bebas sih mau pilih apa aja
  akurasi = []
  formula_1 = []
  temennya_akurasi = []
  recall_recall = []

  # Looping deh
  for model in daftar_model_kita:
    # Tidak perlu fit & predict lagi, langsung kita hitung metricsnya
    akurasi.append(np.mean(cross_val_score(model, X, y, cv = cv_kita, scoring = 'accuracy')))
    formula_1.append(np.mean(cross_val_score(model, X, y, cv = cv_kita, scoring = 'f1')))
    temennya_akurasi.append(np.mean(cross_val_score(model, X, y, cv = cv_kita, scoring = 'precision')))
    recall_recall.append(np.mean(cross_val_score(model, X, y, cv = cv_kita, scoring = 'recall')))

  # Jadiin sebuah dataframe biar keren gituloh
  hasil = {
    'model' : daftar_model_kita,
    'akurasi' : akurasi,
    'f1_score' : formula_1,
    'presisi' : temennya_akurasi,
    'recall' : recall_recall
  }

  # Balikin hasilnya
  return(pd.DataFrame(hasil))

In [ ]:
hasilcv = auto_model_pake_cv(X, y)

d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer

In [ ]:
hasilcv.sort_values(by='akurasi', ascending=False)

                             model   akurasi  f1_score   presisi    recall
2         RandomForestClassifier()  0.804714  0.725596  0.744680  0.708146
3                  MLPClassifier()  0.792368  0.723121  0.729351  0.717696
5  QuadraticDiscriminantAnalysis()  0.791246  0.730197  0.722359  0.738994
4     LinearDiscriminantAnalysis()  0.789001  0.710508  0.744218  0.681083
1         DecisionTreeClassifier()  0.775533  0.701460  0.698655  0.708088
0                            SVC()  0.683502  0.445289  0.676872  0.331956
7               LabelPropagation()  0.659933  0.455631  0.592886  0.372063
8                 LabelSpreading()  0.659933  0.455620  0.593882  0.372063
6  GaussianMixture(n_components=2)  0.572391  0.450950  0.305496  0.605024

### Bonus content

Model di bawah ini juga buat cross validation, cuma lebih sophisticated (lebih rumit utk dijelaskan~)

CalibratedClassifier bisa digunakan untuk meningkatkan performa model apapun yg kita punya

RidgeClassifierCV khusus buat ridge regression (otomatis)

In [ ]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import RidgeClassifierCV

def auto_model_2(x_train, y_train, x_test, y_test):
  # Tulis semua model yg mau dibikin jadi sebuah list kayak gini
  daftar_model_kita = [SVC(), DecisionTreeClassifier(), MLPClassifier(), RandomForestClassifier(), QuadraticDiscriminantAnalysis(), LabelPropagation(), LabelSpreading()]

  # Siapin list buat nyimpen nilai metrics nya, bebas sih mau pilih apa aja
  akurasi = []
  akurasi_kalibrasi = []
  akurasi_jembatan = []

  # Looping deh
  for model in daftar_model_kita:
    # Di fit
    model.fit(x_train, y_train)

    # Di kalibrasi & jembatani
    model_kalibrasi = CalibratedClassifierCV(model, cv = 'prefit').fit(x_train, y_train)
    model_jembatan = RidgeClassifierCV(alphas = [0.3, 1.9, 4.5], cv = 3).fit(x_train, y_train)

    # Prediksi dataset ujian setelah di kalibrasi
    prediksi_model_kita = model.predict(x_test)
    prediksi_model_kalibrasi = model_kalibrasi.predict(x_test)
    prediksi_model_jembatan = model_jembatan.predict(x_test)

    akurasi.append(accuracy_score(y_true = y_test, y_pred = prediksi_model_kita))
    akurasi_kalibrasi.append(accuracy_score(y_true = y_test, y_pred = prediksi_model_kalibrasi))
    akurasi_jembatan.append(accuracy_score(y_true = y_test, y_pred = prediksi_model_jembatan))

  # Jadiin sebuah dataframe biar keren gituloh
  hasil = {
    'model' : daftar_model_kita,
    'akurasi' : akurasi,
    'akurasi_kalibrasi' : akurasi_kalibrasi,
    'akurasi_jembatan' : akurasi_jembatan
  }

  # Balikin hasilnya
  return(pd.DataFrame(hasil))

In [ ]:
hasillagi = auto_model_2(x_train, y_train, x_test, y_test)

d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\calibration.py:333: UserWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer
d:\Anaconda\Lib\site-packages\sklearn\semi_supervised\_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer

In [ ]:
hasillagi.sort_values(by='akurasi', ascending=False)

,model,akurasi,akurasi_kalibrasi,akurasi_jembatan
4,QuadraticDiscriminantAnalysis(),0.836449,0.789720,0.803738
3,"(DecisionTreeClassifier(max_features='sqrt', r...",0.827103,0.845794,0.803738
1,DecisionTreeClassifier(),0.822430,0.822430,0.803738
2,MLPClassifier(),0.771028,0.836449,0.803738
0,SVC(),0.738318,0.728972,0.803738
6,LabelSpreading(),0.663551,0.635514,0.803738
5,LabelPropagation(),0.658879,0.635514,0.803738